###服务端口号
server:
  port: 8100
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
###因为自己是为注册中心，不需要检索服务
    fetch-registry: true
###关闭自我保护机制，假如服务端不发送心跳包直接剔除，间隔2s中剔除一次
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: eureka-server
