###服务启动端口号
server:
  port: 8000
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-itmayiedu-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
###需要将我注册到服务
    register-with-eureka: true
###检索服务
    fetch-registry: true
#####最初复制实例信息到eureka服务器所需的时间（s），默认为40秒
    initial-instance-info-replication-interval-seconds: 2
####  复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
    instance-info-replication-interval-seconds: 2
###心跳间隔设置
  instance:
  ###最小呼气时间，即服务器在收到一个心跳后等待的时间，假如超过2s没收到下个心跳包则剔除
    lease-expiration-duration-in-seconds: 2
  ###心跳间隔，每隔1s发送一个心跳包给服务器
    lease-renewal-interval-in-seconds: 1

