###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: git@github.com:QiuMingJie/springcloud-study.git
          ####搜索目录
          search-paths:
            - config
            #####github账号密码，由于是public的，所以可以直接访问不需要配置这个
#          username: 838689269@qq.com
#          password:
          ####私钥验证的密码
          passphrase: 123456
      ####读取分支
      label: master
####端口号
server:
  port: 8888
